name: rtx5080_3dgs
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - python=3.10
  - pip
  - pytorch::pytorch=2.1.0
  - pytorch::torchvision=0.16.0
  - pytorch::torchaudio=2.1.0
  - numpy<2.0
  - plyfile
  - tqdm
  - websockets
  - pip:
    - lpips
